"""Identify the code that produced a report.

Three consecutive reports were generated by a frozen ``pip install .`` copy in
site-packages while the working tree held the fixes. They looked entirely
normal, and it took a full investigation each time to establish which code had
actually run — comparing report figures against what the current code emits,
because nothing in the output said.

One line in the header answers it. The revision is read from the *package's own
location*, not the working directory, because those are exactly what diverged:
a stale install and a current checkout can sit on the same machine, and asking
the shell's cwd which commit is checked out would have reported the fix as
present on every one of those runs.
"""

from __future__ import annotations

import functools
import subprocess
from pathlib import Path

_GIT_TIMEOUT_SECONDS = 5


def _git(package_dir: Path, *args: str) -> str | None:
    """Run a git command against ``package_dir``; None when it cannot answer."""
    try:
        result = subprocess.run(
            ["git", "-C", str(package_dir), *args],
            capture_output=True, text=True, timeout=_GIT_TIMEOUT_SECONDS,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    return result.stdout.strip() if result.returncode == 0 else None


@functools.lru_cache(maxsize=1)
def code_revision() -> str:
    """Describe the checked-out code this package was imported from.

    Returns a short SHA, marked when the tree carries uncommitted changes, or an
    explicit ``unknown`` naming the import path. That fallback is the case worth
    designing for: an installed copy is not a working tree, so it cannot report
    a revision, and saying where it came from is what identifies it.
    """
    package_dir = Path(__file__).resolve().parent

    # A virtualenv usually lives inside the project, so `git -C` on an installed
    # copy would walk up and cheerfully report the checkout's SHA — the very
    # confusion this exists to end. Tracked-ness is what separates the source
    # tree from a copy of it.
    tracked = _git(package_dir, "ls-files", "--error-unmatch", "__init__.py")
    if tracked is None:
        return f"unknown — imported from {package_dir}"

    revision = _git(package_dir, "rev-parse", "--short", "HEAD")
    if revision is None:
        return f"unknown — imported from {package_dir}"

    if _git(package_dir, "status", "--porcelain"):
        revision += "+local-changes"
    return revision
