"""A saved report must say which code produced it.

Three consecutive reports were generated by a frozen `pip install .` copy in
site-packages while the working tree held the fixes. They looked entirely
normal, and establishing which code had run took a full investigation each time.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

from tradingagents import provenance
from tradingagents.reporting import _split_own_header, write_report_tree


@pytest.mark.unit
class TestCodeRevision:
    def test_the_source_tree_reports_its_sha(self):
        provenance.code_revision.cache_clear()
        revision = provenance.code_revision()
        assert not revision.startswith("unknown")
        assert len(revision.split("+")[0]) >= 7

    def test_an_untracked_copy_refuses_to_borrow_the_checkout_sha(self, monkeypatch, tmp_path):
        # The trap: a virtualenv lives inside the project, so `git -C` on an
        # installed copy walks up and finds the real repo. Reporting that SHA
        # would assert the fix was present on exactly the runs where it was not.
        monkeypatch.setattr(provenance, "__file__", str(tmp_path / "provenance.py"))
        provenance.code_revision.cache_clear()

        revision = provenance.code_revision()
        assert revision.startswith("unknown")
        assert str(tmp_path) in revision

    def test_uncommitted_changes_are_flagged(self, monkeypatch):
        calls = {}

        def fake_git(package_dir: Path, *args: str):
            calls[args[0]] = True
            if args[0] == "ls-files":
                return "__init__.py"
            if args[0] == "rev-parse":
                return "abc1234"
            return " M tradingagents/reporting.py"

        monkeypatch.setattr(provenance, "_git", fake_git)
        provenance.code_revision.cache_clear()
        assert provenance.code_revision() == "abc1234+local-changes"

    def test_a_clean_tree_is_not_flagged(self, monkeypatch):
        def fake_git(package_dir: Path, *args: str):
            return {"ls-files": "__init__.py", "rev-parse": "abc1234"}.get(args[0], "")

        monkeypatch.setattr(provenance, "_git", fake_git)
        provenance.code_revision.cache_clear()
        assert provenance.code_revision() == "abc1234"

    def test_a_missing_git_binary_does_not_raise(self, monkeypatch):
        def boom(*args, **kwargs):
            raise FileNotFoundError("git not installed")

        monkeypatch.setattr(subprocess, "run", boom)
        provenance.code_revision.cache_clear()
        assert provenance.code_revision().startswith("unknown")


@pytest.mark.unit
class TestReportCarriesTheRevision:
    def test_the_header_names_the_code_that_produced_it(self, tmp_path):
        path = write_report_tree({"market_report": "x"}, "INTC", tmp_path)
        header = path.read_text(encoding="utf-8").splitlines()[2]
        assert header.startswith("Generated: ")
        assert " · code " in header

    def test_the_revision_reaches_the_html_subtitle(self, tmp_path):
        text = write_report_tree({"market_report": "x"}, "INTC", tmp_path).read_text(encoding="utf-8")
        body, generated = _split_own_header(text)
        # It rides on the Generated line so the existing header split carries it
        # into the page subtitle rather than leaving it loose in the body.
        assert " · code " in generated
        assert " · code " not in body

    def test_a_provenance_failure_never_costs_the_report(self, tmp_path, monkeypatch):
        # One line saying where the report came from must not be able to lose
        # the report itself.
        def boom():
            raise RuntimeError("git exploded")

        monkeypatch.setattr(provenance, "code_revision", boom)

        path = write_report_tree({"market_report": "x"}, "INTC", tmp_path)
        assert path.exists()
        assert "code unknown" in path.read_text(encoding="utf-8")
